include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    mixin_inherits_from_not_object: ignore
  plugins:
    - custom_lint

linter:
  rules:
    # Performance optimizations
    avoid_print: true
    avoid_returning_null_for_void: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    
    # Code quality
    require_trailing_commas: true
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true
    
    # Existing exceptions
    non_constant_identifier_names: false
    file_names: false
    constant_identifier_names: false
    library_private_types_in_public_api: false
    library_prefixes: false