include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    mixin_inherits_from_not_object: ignore
  plugins:
    - custom_lint

linter:
  rules:
    non_constant_identifier_names: false
    file_names: false
    constant_identifier_names: false
    library_private_types_in_public_api: false
    library_prefixes: false